name: Compiler Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-compiler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -f compiler/Dockerfile -t ghcr.io/binozo/echogosdkcompiler:latest .

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Docker image
        run: docker push ghcr.io/binozo/echogosdkcompiler:latest

      - name: Build the Go compiler image
        run: docker build -t ghcr.io/binozo/echogo:latest .

      - name: Push Go compiler image
        run: docker push ghcr.io/binozo/echogo:latest

  build-server:
    runs-on: ubuntu-latest
    needs: build-compiler

    steps:
      - uses: actions/checkout@v4
      - name: Build server
        run: docker run --env TARGET="server.go" -v "$(pwd)":/EchoGoSDK ghcr.io/binozo/echogo:latest
      - uses: actions/upload-artifact@v4
        with:
          name: Server
          path: build/main
          retention-days: 7
